name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: Avabin/MistTrader
        ref: ${{ github.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: tests/MistTrader.DataParsers.Tests/TestResults/net9.0/MistTrader.DataParsers.Tests.trx

    - name: Test Reporter
      uses: dorny/test-reporter@v1
      with:
        name: test-results
        path: tests/MistTrader.DataParsers.Tests/TestResults/net9.0/MistTrader.DataParsers.Tests.trx
        reporter: dotnet-trx
